### ISSUE TITLE
dataset and storage table

### ISSUE THREAD

**Issue by robinschmid** [mzmine/ms_management_system#1]
### dataset
- id
- name
- description
- acqusition_date
- nfiles - int 

### Storage
Defines where datasets are stored either locally or on data repositories. Name and function up to debate.
Maybe we split into LocalStorage and RepositoryStorage

#### LocalStorage
- id
- dataset.id
- file_path

#### RepositoryStorage
- id
- dataset.id
- repository.id
- accession: str

#### DataRepository
Defines the data repositories. Currently its mostly:
- MetaboLights
- MetabolomicsWorkbench
- GNPS/MassIVE

Schema
- id
- name
- description
- url

**Comment by shamlymhd** [comment]
I've sent the PR for this
